Export AuthKey notarize so I don't get warnings when building a app

diff --git a/.github/workflows/tauri-build.yml b/.github/workflows/tauri-build.yml
--- a/.github/workflows/tauri-build.yml
+++ b/.github/workflows/tauri-build.yml
@@ -36,11 +36,28 @@ jobs:
         with:
           # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
           targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
-      - name: Import Apple Developer Certificate
+      - name: Import Apple Auth Key (MacOS only)
         if: matrix.platform == 'macos-latest'
         env:
-          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
+          APPLE_AUTH_KEY_BASE64: ${{ secrets.APPLE_AUTH_KEY_BASE64 }}
+        run: |
+          echo $APPLE_AUTH_KEY_BASE64 | base64 --decode > AuthKey_78LZT6863R.p8
+      - name: Verify Apple Auth Key (MacOS only)
+        if: matrix.platform == 'macos-latest'
+        run: |
+          first_line=$(head -n 1 AuthKey_78LZT6863R.p8)
+          echo "First line: $first_line"
+          if [[ "$first_line" != "-----BEGIN PRIVATE KEY-----" ]]; then
+            echo "Error: Private key does not start with '-----BEGIN PRIVATE KEY-----'."
+            exit 1
+          fi
+          echo "APPLE_API_KEY_PATH=$PWD/AuthKey_78LZT6863R.p8" >> $GITHUB_ENV
+          echo "Exported APPLE_API_KEY_PATH $PWD/AuthKey_78LZT6863R.p8"
+      - name: Import Apple Developer Certificate (MacOS only)
+        if: matrix.platform == 'macos-latest'
+        env:
           APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
+          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
         run: |
           echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
@@ -50,7 +67,7 @@ jobs:
           security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
           security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
           security find-identity -v -p codesigning build.keychain
-      - name: Verify Certificate
+      - name: Verify Certificate (MacOS only)
         if: matrix.platform == 'macos-latest'
         run: |
           echo "Looking for Developer ID Application..."
